### ISSUE TITLE
can't upgrate node into r-9.1-mainnet

### ISSUE THREAD

**Issue by zacker0515** [Cardinal-Cryptography/aleph-node#1052]
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/81207283/226289796-f73a2c86-3d83-4d0f-b4b3-dba48ca89747.png">

when I run `sudo docker run -ti --volume=$(pwd):/node/build aleph-build` , this error occured, can u help me?

**Comment by fixxxedpoint** [comment]
A quick-fix for it is to change rust version within that docker-based build procedure, i.e.
1. change rust version in `nix/versions.nix`: `rustToolchain = with nixpkgs; overrideRustTarget ( rustChannelOf { date = "2022-10-30"; channel = "nightly"; } );`

2. switch `postConfigure` tag in `default.nix` to:
```
  postConfigure = ''
      ${nixpkgs.lib.optionalString providedCargoHome
         ''
           cp -r ${cargoHome} .cargo_home
           export CARGO_HOME=.cargo_home
         ''
       }
  '';
```
We should include a fix for it in the next release. Sorry for inconvenience.

**Comment by fixxxedpoint** [comment]
Already fixed. Please also check this PR: https://github.com/Cardinal-Cryptography/aleph-node/pull/1258
