### ISSUE TITLE
error: could not compile `schnellru` due to 6 previous errors

### ISSUE THREAD

**Issue by zacker0515** [Cardinal-Cryptography/aleph-node#1327]
![image](https://github.com/Cardinal-Cryptography/aleph-node/assets/81207283/317b2fb2-7514-45a8-a5f6-64bfac28524f)
when I use  mainnet 10.1. I run 'sudo docker run -ti --volume=$(pwd):/node/build aleph-node/build'. I got this error .  hope for your help

**Comment by h4nsu** [comment]
Hi @zacker0515,

Thanks for the report. Is the same problem happening it when you try the most recent release 11.4?

**Comment by zacker0515** [comment]
> Hi @zacker0515,
> 
> Thanks for the report. Is the same problem happening when you try the most recent release 11.4?

when I use 11.4 get the differnet error 'Step 5/9 : COPY default.nix shell.nix rust-toolchain /node/nix-files/
COPY failed: file not found in build context or excluded by .dockerignore: stat rust-toolchain: file does not exist'
when I run 'sudo docker build -t aleph-node/build -f nix/Dockerfile.build .'

**Comment by zacker0515** [comment]
hello If there is any solution to deal with?

**Comment by h4nsu** [comment]
Hi @zacker0515,
I pushed the fix to the `release-11` branch, you should be able to do a clean build of Aleph Node 11.4 after updating your repo.
Version `r-10.1-mainnet` is no longer supported. We advice not to use it.
