### ISSUE TITLE
Not able to make public rpc calls on aleph-nodes

### ISSUE THREAD

**Issue by nikitagugale** [Cardinal-Cryptography/aleph-node#1793]
As per instructions I have aleph-node running(by running scripts/run_nodes.sh), it is accessible  through local host but on deployment to docker /kubernetes I am not able to connect to network through rpc url. (Example: wss://node.mynetwork.in) Is there any flag missing while running the node so that I can access it publically?

**Comment by kostekIV** [comment]
Hi @nikitagugale pleas open this issue [here](https://github.com/Cardinal-Cryptography/aleph-node-issues/issues).
Please, also include more information about your setup there. For example, what exactly are you running, which version etc.
