### ISSUE TITLE
Question: AlephBFT depend on Aura, so Aleph Zero is actually a blockchain. So what is DAG consensus used for?

### ISSUE THREAD

**Issue by hoale58-vl** [Cardinal-Cryptography/aleph-node#335]
Hello guys,
I'm working on doing research about DAG and blockchain. Your project looks promising about the idea but I'm confused about your implementation in this repository.
In FAQ from your official website, you mentioned that Aleph Zero uses DAG consensus protocol so multiple users can create blocks at the same time. But, as I can see you are using created block by Substrate's Aura, which is actually working as a blockchain protocol.
As I understand that AlephBFT only finalizes those blocks created by Aura so it cannot help us to create multiple blocks at the same time. Could you clarify more details about this?

Btw, also in FAQ, you said that your project is different from Hedera Hashgraph because of the number of validators. As I can see in this repository, you haven't implemented any validators election logic for both Aura and AlephBFT. Could you give me more details about this?

**Comment by fbielejec** [comment]
By convention GH Issues are used for reproducible bug reports or feature request.

[Discord](https://discord.gg/hqHT4ffD) and other official channels are generally a better place for these types of questions and informal discussions, could you please raise it there?
